project_id = "owjcahmjbsksoctgfhzo"

[functions.zapier-relay]
verify_jwt = false

[functions.provision-mentorship-student]
verify_jwt = false

[functions.publish-mentorship-feedback]
verify_jwt = true
