import { useRef, useState } from 'react';
import { Link, useParams, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, Download, ExternalLink, Plus, Play, Save, FileText } from 'lucide-react';
import { toast } from 'sonner';
import { StudentAvatar } from '../components/StudentAvatar';
import { SuccessError, SuccessLoading, SuccessPrivacy } from './AdminCohorts';
import {
  loadStudentWorkspace, saveStudentContext, saveStaffNote, addStudentAction, toggleStudentAction,
  saveProgressExample, successMediaUrl, safeSourceUrl, markSurgeryDelivered, successRoot,
  type StudentWorkspace, type SuccessFile, type SuccessNote, type SuccessSurgery,
} from '../studentSuccessApi';
import { audioOptions, fileWeek, localDateInput, studentProgress } from '../studentSuccess';
import '../studentSuccess.css';

type SaveRecord = (work: () => Promise<void>, message: string) => Promise<boolean>;
const tabs = ['Overview', 'Music', 'Calls & notes', 'Follow-ups'] as const;
const dateLabel = (value: string | null | undefined) => value ? new Date(value.length === 10 ? `${value}T12:00:00` : value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Not set';

export function AdminStudentRecord() {
  const { cohortId = '', enrollmentId = '' } = useParams();
  const [params, setParams] = useSearchParams();
  const selected = params.get('tab') || 'Overview';
  const tab = tabs.find(t => t === selected) ?? 'Overview';
  const cache = useQueryClient();
  const query = useQuery({ queryKey: ['success-student', cohortId, enrollmentId], queryFn: () => loadStudentWorkspace(cohortId, enrollmentId) });
  const savingRef = useRef(false);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const save: SaveRecord = async (work, message) => {
    if (savingRef.current) return false;
    savingRef.current = true; setSaving(true); setSaveError('');
    try {
      await work();
      await cache.invalidateQueries({ queryKey: ['success-student', cohortId, enrollmentId] });
      void cache.invalidateQueries({ queryKey: ['success-cohort', cohortId] });
      toast.success(message); return true;
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Could not save. Please try again.';
      setSaveError(message); return false;
    } finally { savingRef.current = false; setSaving(false); }
  };
  const data = query.data;
  if (query.isPending) return <section className="student-success"><SuccessLoading/></section>;
  if (query.isError || !data) return <section className="student-success"><Link className="ss-back" to={`${successRoot}/${cohortId}`}><ArrowLeft size={15}/> Back to students</Link><SuccessError error={query.error} retry={() => void query.refetch()}/></section>;
  const { student } = data;
  const progress = studentProgress(data, student);
  const go = (next: string) => setParams({ tab: next });
  return <section className="student-success" key={enrollmentId}>
    <Link className="ss-back" to={`${successRoot}/${cohortId}`}><ArrowLeft size={15}/> {data.cohort.internal_name} students</Link><SuccessPrivacy/>
    <header className="ss-profile-header"><StudentAvatar name={student.name} src={student.profile?.photoUrl} size={92} member={Boolean(student.profile?.completedAt)}/><div className="ss-profile-heading"><div className="ss-row"><h1>{student.name}</h1><span className="ss-badge">{student.is_walkthrough ? 'Your test student' : student.status}</span></div><p>{[student.profile?.artistName, student.profile?.daw].filter(Boolean).join(' · ') || 'Student profile'}</p><div className="ss-profile-links"><a href={`mailto:${student.email}`}>{student.email}</a>{student.profile?.instagram && <a href={`https://instagram.com/${student.profile.instagram}`} target="_blank" rel="noreferrer">@{student.profile.instagram} <ExternalLink size={12}/></a>}{safeSourceUrl(student.profile?.musicUrl ?? null) && <a href={safeSourceUrl(student.profile?.musicUrl ?? null)} target="_blank" rel="noreferrer">Music profile <ExternalLink size={12}/></a>}</div></div></header>
    <div className="ss-stats"><div><strong>{progress.submitted}/6</strong><span>Weeks submitted</span></div><div><strong>{progress.starters}</strong><span>Song starters</span></div><div><strong>{progress.surgeries}</strong><span>Live surgeries completed</span></div><div><strong>{progress.actions.length}</strong><span>Open follow-ups</span></div></div>
    <nav className="ss-tabs" aria-label="Student record sections">{tabs.map(t => <button key={t} type="button" onClick={() => go(t)} aria-current={tab === t ? 'page' : undefined}>{t}{t === 'Follow-ups' && progress.actions.length > 0 && <span>{progress.actions.length}</span>}</button>)}</nav>
    {saveError && <div className="ss-error" role="alert">{saveError}</div>}
    <fieldset disabled={saving} className="ss-record-body" aria-busy={saving}>
      {tab === 'Overview' && <div className="ss-columns"><div className="ss-stack"><ContextCard data={data} save={save}/><section className="ss-card"><h2>Recent notes</h2>{data.notes.length ? [...data.notes].sort((a,b) => b.occurred_on.localeCompare(a.occurred_on)).slice(0,3).map(n => <div className="ss-note-preview" key={n.id}><span className="ss-muted">{dateLabel(n.occurred_on)} · {n.kind === 'note' ? 'Staff note' : `${n.kind} call`}</span><h3>{n.title}</h3><p>{n.body.slice(0,220)}{n.body.length > 220 ? '…' : ''}</p></div>) : <p className="ss-empty-small">No notes yet. Add their goals and context from the onboarding call.</p>}<button className="ss-link" onClick={() => go('Calls & notes')}>Open calls & notes <ArrowRight size={15}/></button></section></div><div className="ss-stack"><section className="ss-card"><h2>Needs attention</h2>{progress.missingWeeks.length > 0 && <p className="ss-warning ss-callout">Submission overdue for week {progress.missingWeeks.map(w => w.week_number).join(', ')}.</p>}{progress.reviews > 0 && <p className="ss-callout">{progress.reviews} submission{progress.reviews === 1 ? '' : 's'} awaiting feedback. <button className="ss-link" onClick={() => go('Music')}>View music</button></p>}{progress.actions.map(a => <div key={a.id} className="ss-note-preview"><h3>{a.title}</h3><p>{data.staff.find(s => s.user_id === a.owner_id)?.full_name || 'Unassigned'}{a.due_on ? ` · Due ${dateLabel(a.due_on)}` : ''}</p></div>)}{!progress.needsAttention && <p className="ss-empty-small">No open follow-ups or overdue submissions.</p>}<button className="ss-button" onClick={() => go('Follow-ups')}><Plus size={15}/> Add follow-up</button></section><section className="ss-card"><h2>Live calls</h2><p>{data.attendance.filter(a => a.attended).length} attendance records marked attended.</p><p className="ss-muted">An unmarked call is not counted as an absence.</p><button className="ss-link" onClick={() => go('Calls & notes')}>View call history <ArrowRight size={15}/></button></section></div></div>}
      {tab === 'Music' && <MusicTab data={data} save={save}/>}
      {tab === 'Calls & notes' && <NotesTab key={enrollmentId} data={data} save={save}/>}
      {tab === 'Follow-ups' && <ActionsTab key={enrollmentId} data={data} save={save}/>}
    </fieldset>
  </section>;
}

function ContextCard({ data, save }: { data: StudentWorkspace; save: SaveRecord }) {
  const [editing, setEditing] = useState(false);
  const [previous, setPrevious] = useState(data.context);
  const [goals, setGoals] = useState(data.context?.goals ?? '');
  const [focus, setFocus] = useState(data.context?.current_focus ?? '');
  const startEdit = () => { setPrevious(data.context); setGoals(data.context?.goals ?? ''); setFocus(data.context?.current_focus ?? ''); setEditing(true); };
  return <section className="ss-card"><div className="ss-row"><h2>Goals & current focus</h2>{!editing && <button onClick={startEdit} className="ss-button">{data.context ? 'Edit' : 'Add context'}</button>}</div>
    {editing ? <form onSubmit={async e => { e.preventDefault(); if (await save(() => saveStudentContext(data.student.id, goals, focus, previous), 'Student context saved.')) setEditing(false); }} className="ss-form"><label className="ss-field">What they want to achieve<textarea value={goals} onChange={e => setGoals(e.target.value)} maxLength={10000} rows={4}/></label><label className="ss-field">What they are working on now<textarea value={focus} onChange={e => setFocus(e.target.value)} maxLength={10000} rows={4}/></label><div className="ss-row"><button className="ss-button ss-primary" type="submit"><Save size={15}/> Save context</button><button type="button" className="ss-button" onClick={() => setEditing(false)}>Cancel</button></div></form> : <><h3 className="ss-section-label">What they want to achieve</h3><p className="ss-prose">{data.context?.goals || 'Not recorded yet.'}</p><h3 className="ss-section-label">Current focus</h3><p className="ss-prose">{data.context?.current_focus || 'Not recorded yet.'}</p>{data.context && <p className="ss-muted">Updated {dateLabel(data.context.updated_at)} · Staff notes</p>}</>}
  </section>;
}

function AudioFile({ file, label, feedback = false }: { file: { storage_path: string; file_name: string }; label?: string; feedback?: boolean }) {
  const [url, setUrl] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const open = async () => { setBusy(true); setError(''); try { setUrl(await successMediaUrl(file.storage_path, feedback)); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to load audio.'); } finally { setBusy(false); } };
  return <div className="ss-audio"><div className="ss-row"><div><span className="ss-muted">{label}</span><strong>{file.file_name}</strong></div>{!url && <button className="ss-button" type="button" disabled={busy} onClick={() => void open()}><Play size={14}/>{busy ? 'Loading…' : 'Listen / download'}</button>}</div>{url && <><audio controls preload="none" src={url} aria-label={file.file_name} onError={() => { setError('Audio could not be loaded. Try reopening the file.'); setUrl(''); }}/><a href={url} download={file.file_name} target="_blank" rel="noreferrer" className="ss-link"><Download size={14}/> Download audio</a></>}{error && <p className="ss-error" role="alert">{error}</p>}</div>;
}
function StemsFile({ file }: { file: SuccessFile }) {
  const [url, setUrl] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const open = async () => { setBusy(true); setError(''); try { setUrl(await successMediaUrl(file.storage_path)); } catch { setError('Unable to open stems. Please try again.'); } finally { setBusy(false); } };
  return <div className="ss-file-row"><FileText size={18}/><span>{file.file_name}</span>{url ? <a href={url} download={file.file_name} target="_blank" rel="noreferrer" className="ss-button"><Download size={14}/> Download ZIP</a> : <button onClick={() => void open()} className="ss-button" disabled={busy}>{busy ? 'Loading…' : 'Get stems'}</button>}{error && <p role="alert">{error}</p>}</div>;
}
function SurgeryStatus({ surgery, save }: { surgery: SuccessSurgery; save: SaveRecord }) {
  const [editing, setEditing] = useState(false); const [date, setDate] = useState(localDateInput());
  return <div className="ss-surgery">{surgery.delivered_at ? <span><Check size={15}/> Live surgery completed {dateLabel(surgery.delivered_at)}</span> : <><span>Shortlisted for a live surgery</span>{editing ? <form className="ss-inline-form" onSubmit={async e => { e.preventDefault(); if(await save(() => markSurgeryDelivered(surgery, `${date}T00:00:00`), 'Live surgery marked completed.')) setEditing(false); }}><label className="ss-field">Date completed<input type="date" required max={localDateInput()} value={date} onChange={e => setDate(e.target.value)}/></label><button className="ss-button" type="submit">Confirm completed</button><button className="ss-button" type="button" onClick={() => setEditing(false)}>Cancel</button></form> : <button className="ss-button" onClick={() => setEditing(true)}>Mark as completed</button>}</>}</div>;
}
function MusicTab({ data, save }: { data: StudentWorkspace; save: SaveRecord }) {
  return <div className="ss-stack"><Comparison data={data} save={save}/><div className="ss-row"><h2>All weekly uploads</h2><span className="ss-muted">{data.files.length} files · Original uploads</span></div>{data.weeks.map(week => {
    const submission = data.submissions.find(s => s.week_id === week.id);
    const files = data.files.filter(f => f.submission_id === submission?.id);
    const feedback = data.feedback.find(f => f.submission_id === submission?.id);
    const surgery = data.surgeries.find(s => s.submission_id === submission?.id);
    const isFuture = week.opens_at && new Date(week.opens_at) > new Date();
    return <details className="ss-card ss-week" key={week.id} open={files.length > 0 ? true : undefined}><summary><span>Week {week.week_number}</span><span className="ss-muted">{files.length} files</span><span className="ss-badge">{submission?.submitted_at ? `Submitted ${dateLabel(submission.submitted_at)}` : files.length ? 'Draft uploads' : isFuture ? 'Upcoming' : 'No uploads yet'}</span></summary><div className="ss-week-content">{!files.length && <p className="ss-empty-small">No files uploaded for this week.</p>}{files.filter(f => f.kind === 'song').map(f => <AudioFile key={f.id} file={f} label="Weekly song"/>)}{files.some(f => f.kind === 'idea') && <details className="ss-loop-list"><summary>Song starters ({files.filter(f => f.kind === 'idea').length})</summary>{files.filter(f => f.kind === 'idea').map(f => <AudioFile key={f.id} file={f} label="Song starter"/>)}</details>}{files.filter(f => f.kind === 'stems').map(f => <StemsFile key={f.id} file={f}/>)}
      {feedback && <section className="ss-feedback"><div className="ss-row"><h3>Rob’s feedback</h3><span className="ss-badge">{feedback.status}</span></div><p className="ss-prose">{feedback.written_notes || 'No written notes.'}</p>{feedback.next_action && <><h4>Next action</h4><p className="ss-prose">{feedback.next_action}</p></>}{feedback.audio_storage_path && <AudioFile file={{ storage_path: feedback.audio_storage_path, file_name: 'Voice feedback' }} feedback/>}{safeSourceUrl(feedback.video_url) && <a className="ss-link" href={safeSourceUrl(feedback.video_url)} target="_blank" rel="noreferrer">Open video feedback <ExternalLink size={14}/></a>}{feedback.action_confirmed_at && <p className="ss-muted">Student confirmed their next action on {dateLabel(feedback.action_confirmed_at)}: {feedback.student_next_action}</p>}</section>}
      {surgery && <SurgeryStatus surgery={surgery} save={save}/>}{submission?.submitted_at && <Link className="ss-link" to={`/mentorship-portal/admin/review/${submission.id}`}>{feedback?.status === 'published' ? 'Open feedback workspace' : 'Review submission'} <ArrowRight size={15}/></Link>}
    </div></details>;
  })}</div>;
}
function Comparison({ data, save }: { data: StudentWorkspace; save: SaveRecord }) {
  const files = audioOptions(data); const [before, setBefore] = useState(''); const [after, setAfter] = useState(''); const [title, setTitle] = useState('');
  const label = (f: SuccessFile) => `Week ${fileWeek(data, f)} · ${f.kind === 'idea' ? 'Starter' : 'Song'} · ${f.file_name}`;
  const first = files.find(f => f.id === before), second = files.find(f => f.id === after);
  return <section className="ss-card"><div className="ss-row"><h2>Compare progress</h2><span className="ss-badge">Staff only</span></div><p>Listen to two uploads side by side. Save a comparison to revisit with Rob.</p>{files.length < 2 ? <p className="ss-empty-small">This student needs at least two audio uploads to compare.</p> : <><div className="ss-compare-grid">{(['Earlier upload', 'Later upload'] as const).map((name, i) => <div key={name}><label className="ss-field">{name}<select value={i ? after : before} onChange={e => i ? setAfter(e.target.value) : setBefore(e.target.value)}><option value="">Choose an upload</option>{files.map(f => <option key={f.id} value={f.id}>{label(f)}</option>)}</select></label>{(i ? second : first) && <AudioFile key={i ? after : before} file={(i ? second : first)!}/>}</div>)}</div>{before && after && before !== after && <form className="ss-inline-form" onSubmit={async e => { e.preventDefault(); if (await save(() => saveProgressExample(data.student.id, title, before, after), 'Progress example saved.')) setTitle(''); }}><label className="ss-field ss-grow">Name this comparison<input value={title} onChange={e => setTitle(e.target.value)} required maxLength={180} placeholder="e.g. Stronger chorus arrangement"/></label><button className="ss-button" type="submit"><Save size={14}/> Save comparison</button></form>}</>}{data.examples.length > 0 && <div className="ss-saved-examples"><h3>Saved comparisons</h3>{data.examples.map(example => <button className="ss-example" key={example.id} onClick={() => { setBefore(example.before_file_id); setAfter(example.after_file_id); }}><span><strong>{example.title}</strong><span>{dateLabel(example.created_at)}</span></span><Play size={15}/></button>)}</div>}</section>;
}

function NotesTab({ data, save }: { data: StudentWorkspace; save: SaveRecord }) {
  const [editing, setEditing] = useState<SuccessNote | 'new'>();
  const notes = [...data.notes].sort((a,b) => b.occurred_on.localeCompare(a.occurred_on) || b.created_at.localeCompare(a.created_at));
  const pastCalls = data.calls.filter(c => new Date(c.starts_at) < new Date() && (c.call_type !== 'onboarding' || data.attendance.some(a => a.call_id === c.id) || data.notes.some(n => n.call_id === c.id)));
  return <div className="ss-columns"><div className="ss-stack"><div className="ss-row"><h2>Calls & notes</h2><button className="ss-button ss-primary" onClick={() => setEditing('new')}><Plus size={15}/> Add note</button></div><div className="ss-notice"><strong>Automatic call capture is not connected.</strong><p>You can add a recording link, transcript and notes here in the meantime.</p></div>{editing && <NoteEditor key={editing === 'new' ? 'new' : editing.id} data={data} previous={editing === 'new' ? undefined : editing} save={save} close={() => setEditing(undefined)}/>}{notes.map(note => <article className="ss-card" key={note.id}><div className="ss-row"><span className="ss-badge">{note.kind === 'note' ? 'Staff note' : note.kind === 'onboarding' ? 'Onboarding call' : 'Group call'}</span><button className="ss-button" onClick={() => setEditing(note)}>Edit</button></div><h2>{note.title}</h2><p className="ss-muted">{dateLabel(note.occurred_on)} · Added by {data.staff.find(p => p.user_id === note.created_by)?.full_name || 'Staff'}</p><p className="ss-prose">{note.body}</p>{safeSourceUrl(note.source_url) && <a className="ss-link" href={safeSourceUrl(note.source_url)} target="_blank" rel="noreferrer">Open source recording <ExternalLink size={14}/></a>}{note.transcript && <details className="ss-transcript"><summary>Read transcript / relevant excerpt</summary><p className="ss-prose">{note.transcript}</p></details>}</article>)}{!notes.length && !editing && <div className="ss-empty">No notes yet. Start with the onboarding call and what this student wants to achieve.</div>}</div><aside className="ss-card"><h2>Call attendance</h2><p className="ss-muted">Saved attendance records. Unmarked calls need checking.</p>{pastCalls.map(call => { const record = data.attendance.find(a => a.call_id === call.id); return <div key={call.id} className="ss-note-preview"><h3>{call.title}</h3><p>{dateLabel(call.starts_at)}</p><span className="ss-badge">{record ? record.attended ? `Attended${record.minutes_attended ? ` · ${record.minutes_attended} min` : ''}` : 'Marked absent' : 'Not recorded'}</span></div>; })}{!pastCalls.length && <p className="ss-empty-small">No past calls recorded.</p>}</aside></div>;
}
function NoteEditor({ data, previous, save, close }: { data: StudentWorkspace; previous?: SuccessNote; save: SaveRecord; close: () => void }) {
  const [kind, setKind] = useState<SuccessNote['kind']>(previous?.kind ?? 'note'); const [title, setTitle] = useState(previous?.title ?? ''); const [body, setBody] = useState(previous?.body ?? ''); const [transcript, setTranscript] = useState(previous?.transcript ?? ''); const [source, setSource] = useState(previous?.source_url ?? ''); const [date, setDate] = useState(previous?.occurred_on ?? localDateInput()); const [call, setCall] = useState(previous?.call_id ?? '');
  return <form className="ss-card ss-form" onSubmit={async e => { e.preventDefault(); if (await save(() => saveStaffNote(data.student.id, { kind, title, body, transcript, source_url: source.trim() || null, occurred_on: date, call_id: call || null }, previous), 'Staff note saved.')) close(); }}><h2>{previous ? 'Edit note' : 'Add note'}</h2><div className="ss-compare-grid"><label className="ss-field">Type<select value={kind} onChange={e => setKind(e.target.value as SuccessNote['kind'])}><option value="note">Staff note</option><option value="onboarding">Onboarding call</option><option value="group">Group call</option></select></label><label className="ss-field">Date<input type="date" value={date} required onChange={e => setDate(e.target.value)}/></label></div><label className="ss-field">Title<input value={title} onChange={e => setTitle(e.target.value)} required maxLength={180}/></label><label className="ss-field">Notes<textarea value={body} onChange={e => setBody(e.target.value)} maxLength={50000} rows={5} placeholder="What matters for this student, what was agreed, and what needs following up."/></label>{kind !== 'note' && <><label className="ss-field">Link to a scheduled call (optional)<select value={call} onChange={e => setCall(e.target.value)}><option value="">No scheduled call selected</option>{data.calls.map(c => <option key={c.id} value={c.id}>{dateLabel(c.starts_at)} · {c.title}</option>)}</select></label><label className="ss-field">Recording link (optional)<input type="url" value={source} onChange={e => setSource(e.target.value)} placeholder="https://…" maxLength={2048}/></label><label className="ss-field">Transcript or relevant excerpt (optional)<textarea value={transcript} onChange={e => setTranscript(e.target.value)} rows={5} maxLength={500000}/><span className="ss-muted">For group calls, add only the discussion relevant to this student.</span></label></>}<div className="ss-row"><button className="ss-button ss-primary" type="submit">Save note</button><button className="ss-button" type="button" onClick={close}>Cancel</button></div></form>;
}
function ActionsTab({ data, save }: { data: StudentWorkspace; save: SaveRecord }) {
  const [title, setTitle] = useState(''); const [owner, setOwner] = useState(''); const [due, setDue] = useState('');
  const actions = [...data.actions].sort((a,b) => Number(Boolean(a.completed_at)) - Number(Boolean(b.completed_at)) || (a.due_on ?? '9999').localeCompare(b.due_on ?? '9999'));
  return <div className="ss-stack"><section className="ss-card"><h2>Add follow-up</h2><p>Assign an action to Rob, George or another staff member. These are internal tasks and do not send messages to the student.</p><form className="ss-form" onSubmit={async e => { e.preventDefault(); if(await save(() => addStudentAction(data.student.id, title, owner, due), 'Follow-up saved.')) { setTitle(''); setDue(''); } }}><label className="ss-field">What needs doing?<input value={title} onChange={e => setTitle(e.target.value)} required maxLength={1000} placeholder="e.g. Check in about the week 2 arrangement"/></label><div className="ss-inline-form"><label className="ss-field ss-grow">Owner<select value={owner} onChange={e => setOwner(e.target.value)}><option value="">Unassigned</option>{data.staff.map(p => <option key={p.user_id} value={p.user_id}>{p.full_name}</option>)}</select></label><label className="ss-field">Due date (optional)<input type="date" value={due} onChange={e => setDue(e.target.value)}/></label><button className="ss-button ss-primary" type="submit"><Plus size={15}/> Add follow-up</button></div></form></section><section className="ss-card"><h2>Follow-ups</h2>{actions.map(action => <div className="ss-action" key={action.id}><button className="ss-check" aria-label={action.completed_at ? `Reopen: ${action.title}` : `Complete: ${action.title}`} aria-pressed={Boolean(action.completed_at)} onClick={() => void save(() => toggleStudentAction(action), action.completed_at ? 'Follow-up reopened.' : 'Follow-up completed.')}>{action.completed_at && <Check size={17}/>}</button><div><strong className={action.completed_at ? 'ss-done' : ''}>{action.title}</strong><p>{data.staff.find(p => p.user_id === action.owner_id)?.full_name || 'Unassigned'}{action.due_on && <span className={!action.completed_at && action.due_on < localDateInput() ? 'ss-warning' : ''}> · Due {dateLabel(action.due_on)}</span>}{action.completed_at && <span> · Completed {dateLabel(action.completed_at)}</span>}</p></div></div>)}{!actions.length && <p className="ss-empty-small">No follow-ups yet.</p>}</section></div>;
}
