import { useEffect, useState } from 'react';
import { Link, useLocation, useSearchParams } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, Check, ChevronRight, Clock3, Columns3, List, Plus, Search, Users, Link2, CalendarDays, RefreshCw } from 'lucide-react';
import { Sheet, SheetContent, SheetDescription, SheetTitle } from '@/components/ui/sheet';
import { toast } from 'sonner';
import { Calendar } from '@/components/ui/calendar';
import { usePortalStore } from '../PortalStore';
import { StudentAvatar } from '../components/StudentAvatar';
import { SuccessError, SuccessLoading } from './AdminCohorts';
import { loadSuccessCohorts, successRoot, type StaffPerson } from '../studentSuccessApi';
import { crmRoot, leadStages, leadSources, leadChannels, blankLead, dueState, leadStage, localDay, localDateTime, onboardingState, readableDate, type Lead, type LeadInput, type LeadStage } from '../crm';
import { loadCrm, saveLead, leadInput, loadLeadActivity, addLeadNote, saveOnboardingCall, type CrmStudent, type CrmWorkspace } from '../crmApi';
import '../studentSuccess.css';
import '../crm.css';
import { hasPaid, launchAnalytics, type FunnelStep } from '../crmAnalytics';
import { LaunchOverview, LaunchTargetsPanel, LeadPayments } from './AdminCrmOverview';
import { TypeformConnectionForm } from '../components/TypeformConnectionForm';

const errorText=(e:unknown)=>e instanceof Error?e.message:'Unable to save. Please try again.';
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:string}) { return <span className={`crm-badge crm-${tone}`}>{children}</span>; }
function useDirtyWarning(dirty:boolean) { useEffect(()=>{ if(!dirty)return; const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';}; window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn); },[dirty]); }
const studentLink=(s:CrmStudent)=>`${successRoot}/${s.cohort_id}/students/${s.id}?tab=Onboarding`;
export function AdminCrm() {
  const [params,setParams]=useSearchParams(); const location=useLocation(); const onboarding=location.pathname.endsWith('/onboarding'); const overview=location.pathname.endsWith('/overview');
  const {user}=usePortalStore(); const cache=useQueryClient();
  const cohorts=useQuery({queryKey:['success-cohorts'],queryFn:loadSuccessCohorts});
  const chosen=params.get('cohort'); const cohortId=cohorts.data?.find(c=>c.id===chosen)?.id??[...(cohorts.data??[])].reverse().find(c=>!['archived','completed'].includes(c.status))?.id??cohorts.data?.[0]?.id??'';
  const query=useQuery({queryKey:['crm',cohortId],queryFn:()=>loadCrm(cohortId),enabled:!!cohortId,refetchInterval:60000});
  const [newLead,setNewLead]=useState(false); const [booking,setBooking]=useState<CrmStudent|null>(null); const [connections,setConnections]=useState(false); const [capacityOpen,setCapacityOpen]=useState(false);
  const selected=query.data?.leads.find(l=>l.id===params.get('lead'));
  const openLead=(id:string)=>setParams(p=>{p.set('cohort',cohortId);p.set('lead',id);return p;});
  const closeLead=()=>{setNewLead(false);setParams(p=>{p.delete('lead');return p;},{replace:true});};
  const refresh=async()=>{await cache.invalidateQueries({queryKey:['crm',cohortId]});};
  const data=query.data; const real=data?.students.filter(s=>!s.is_walkthrough&&s.status==='active')??[];
  const activeIds=new Set(data?.students.filter(s=>s.status==='active'&&!s.is_walkthrough).map(s=>s.id));
  const open=data?.leads.filter(l=>!['enrolled','closed'].includes(leadStage(l,activeIds))&&!hasPaid(l,data.payments))??[];
  const due=open.filter(l=>['today','overdue'].includes(dueState(l.due_on))).length;
  const paid=data?.leads.filter(l=>hasPaid(l,data.payments)&&l.stage!=='closed').length??0;
  const finished=real.filter(s=>onboardingState(s.call,s.questionnaire,s.focus).key==='complete').length;
  return <section className="student-success crm-workspace">
    <div className="crm-topline"><span>MENTORSHIP / ADMISSIONS</span><div className="crm-inline"><button className="crm-text-button" onClick={()=>setConnections(true)}><Link2 size={14}/> Connections</button><button className="crm-icon-button" aria-label="Refresh admissions" disabled={query.isFetching} onClick={()=>void refresh()}><RefreshCw size={15} className={query.isFetching?'crm-spin':''}/></button></div></div>
    <header className="crm-heading"><div><h1>Leads & onboarding</h1><p>Track the launch, move applications forward and get students ready.</p></div><div className="crm-inline"><label className="ss-field"><span className="sr-only">Cohort</span><select aria-label="Cohort" value={cohortId} onChange={e=>setParams({cohort:e.target.value})}>{cohorts.data?.map(c=><option key={c.id} value={c.id}>{c.internal_name}</option>)}</select></label><button className="ss-button ss-primary" disabled={!data} onClick={()=>setNewLead(true)}><Plus size={16}/> Add lead</button></div></header>
    {cohorts.isError?<SuccessError error={cohorts.error} retry={()=>void cohorts.refetch()}/>:cohorts.isPending?<SuccessLoading/>:!cohortId?<div className="ss-empty">Create a cohort before adding leads.</div>:query.isPending?<SuccessLoading/>:query.isError?<SuccessError error={query.error} retry={()=>void refresh()}/>:data&&<>
      <nav className="crm-tabs crm-main-tabs" aria-label="Admissions workspace"><Link aria-current={overview?'page':undefined} to={`${crmRoot}/overview?cohort=${cohortId}`}>Launch overview</Link><Link aria-current={!onboarding&&!overview?'page':undefined} to={`${crmRoot}/leads?cohort=${cohortId}`}>Leads <span>{data.leads.length}</span></Link><Link aria-current={onboarding?'page':undefined} to={`${crmRoot}/onboarding?cohort=${cohortId}`}>Onboarding <span>{real.length-finished}</span></Link></nav>
      {data.intake.length>0&&<div className="crm-intake-status">{data.intake.map(c=><button key={c.provider} type="button" onClick={()=>setConnections(true)}><span className={`crm-connection-dot ${c.status==='connected'?'crm-dot-connected':''}`}/><strong>{c.provider==='gmail'?'Gmail':'Typeform'}</strong><span>{c.status==='connected'?'Connected':c.status==='backfilled'?'Imported · automatic sync pending':c.status==='error'?'Needs attention':c.status==='paused'?'Paused':'Not connected'}</span><ChevronRight size={13}/></button>)}</div>}
      {overview?<LaunchOverview data={data} cohortId={cohortId} editTargets={()=>setCapacityOpen(true)} openLead={openLead}/>:<><div className="crm-queue-summary"><div><h2>{onboarding?'Student onboarding':'Lead workspace'}</h2><p>{onboarding?'Arrange calls and complete each student’s questionnaire.':'Open a contact to reply, review their application or record a payment.'}</p></div><div className="crm-inline"><span><strong>{onboarding?real.length-finished:due}</strong> {onboarding?'to complete':'follow-ups due'}</span><span><strong>{paid}/{data.capacity}</strong> places filled</span></div></div>{onboarding?<OnboardingQueue key={cohortId} data={data} onBooking={setBooking}/>:<LeadQueue key={`${cohortId}:${params.get('queue')}:${params.get('stage')}:${params.get('source')}:${params.get('milestone')}`} data={data} userId={user?.id??''} openLead={openLead} addLead={()=>setNewLead(true)} refresh={refresh}/>}</>}

    </>}
    {data&&(newLead||selected)&&<LeadPanel key={selected?.id??'new'} lead={selected} cohortId={cohortId} staff={data.staff} activeIds={activeIds} data={data} refresh={refresh} onClose={closeLead} onSaved={async l=>{setNewLead(false);await refresh();openLead(l.id);}}/>}
    {booking&&data&&<BookingPanel key={booking.id} student={booking} staff={data.staff} close={()=>setBooking(null)} saved={async()=>{await refresh();setBooking(null);}}/>}
    {capacityOpen&&data&&<LaunchTargetsPanel cohortId={cohortId} settings={data.settings} close={()=>setCapacityOpen(false)} saved={async()=>{await refresh();setCapacityOpen(false);}}/>}
    <Sheet open={connections} onOpenChange={setConnections}><SheetContent className="student-success crm-drawer"><SheetTitle>Connections</SheetTitle><SheetDescription>What is currently connected to this workspace.</SheetDescription><div className="crm-connection"><Badge tone="green">Connected</Badge><h3>Student records</h3><p>Enrolled students appear in Onboarding automatically. Matching lead records are linked by email and cohort.</p></div><div className="crm-connection"><Badge tone="amber">Setup needed</Badge><h3>Shopify payments and account access</h3><p>Shopify payment sync and the welcome email are awaiting connection and a full test. Payment records here are entered by staff.</p></div>{(['gmail','typeform'] as const).map(provider=>{const connection=data?.intake.find(c=>c.provider===provider);const state=connection?.status??'setup_needed';return <div className="crm-connection" key={provider}><Badge tone={state==='connected'?'green':state==='backfilled'?'blue':'amber'}>{state==='connected'?'Connected':state==='backfilled'?'Imported, automation pending':state==='paused'?'Paused':state==='error'?'Needs attention':'Setup needed'}</Badge><h3>{provider==='gmail'?'Gmail handraisers':'Typeform applications'}</h3>{connection?.account_label&&<strong>{connection.account_label}</strong>}<p>{connection?.detail||(provider==='gmail'?'Connect the team inbox to capture new mentorship enquiries.':'Connect the application form to capture new responses.')}</p>{connection?.last_checked_at&&<small>Last checked {readableDate(connection.last_checked_at,true)}</small>}{provider==='typeform'&&user?.role==='admin'&&state!=='connected'&&<TypeformConnectionForm cohortId={cohortId} onConnected={refresh}/>}</div>;})}<p className="crm-footnote">An offer-doc view alone does not identify a lead. Original attribution stays on the contact when they later apply.</p><div className="crm-connection"><Badge tone="amber">Setup needed</Badge><h3>Bookings and call transcripts</h3><p>Record bookings in Onboarding. Fathom capture and AI additions to questionnaires still need connecting.</p></div></SheetContent></Sheet>
  </section>;
}

function LeadQueue({data,userId,openLead,addLead,refresh}:{data:CrmWorkspace;userId:string;openLead:(id:string)=>void;addLead:()=>void;refresh:()=>Promise<void>}) {
  const [params,setParams]=useSearchParams();const [search,setSearch]=useState('');const [filter,setFilter]=useState(params.get('queue')??'all');const [source,setSource]=useState(params.get('source')??'all');const [stage,setStage]=useState(params.get('stage')??'all');const [view,setView]=useState('list');const [moving,setMoving]=useState('');const [drop,setDrop]=useState('');
  const active=new Set(data.students.filter(s=>!s.is_walkthrough&&s.status==='active').map(s=>s.id));
  const milestones=launchAnalytics(data.leads,data.milestones,data.payments,data.students);
  const milestone=params.get('milestone') as FunnelStep|null;const reached=milestone?milestones.ids[milestone]:null;
  const displayStage=(l:Lead)=>leadStage(l,active)==='enrolled'?'enrolled':l.stage!=='closed'&&hasPaid(l,data.payments)?'paid':l.stage;
  const found=data.leads.filter(l=>[l.full_name,l.email,l.source,l.source_detail,l.first_contact_channel].join(' ').toLowerCase().includes(search.toLowerCase())&&(source==='all'||l.source===source)&&(!reached||reached.has(l.id))&&(stage==='all'||displayStage(l)===stage)&&(filter==='all'||filter==='interest'&&['new','waitlist'].includes(displayStage(l))||filter==='mine'&&l.owner_id===userId||filter==='due'&&l.stage!=='closed'&&!['enrolled','paid'].includes(displayStage(l))&&['today','overdue'].includes(dueState(l.due_on))))
    .sort((a,b)=>(a.due_on??'9999').localeCompare(b.due_on??'9999')||b.created_at.localeCompare(a.created_at));
  const move=async(id:string,to:string)=>{const l=data.leads.find(x=>x.id===id);setDrop('');if(!l||['enrolled','paid'].includes(to)||['enrolled','paid'].includes(displayStage(l))||l.stage===to||moving)return;setMoving(id);try{await saveLead({...leadInput(l),stage:to as LeadStage},l);await refresh();toast.success(`Moved to ${leadStages[to as LeadStage]}.`);}catch(e){toast.error(errorText(e));}finally{setMoving('');}};
  return <>
    {reached&&milestone&&<div className="crm-filter-context"><span>Funnel: <strong>{milestones.steps.find(s=>s.key===milestone)?.label}</strong> · everyone who reached this stage, including closed contacts</span><button onClick={()=>setParams(p=>{p.delete('milestone');return p;})}>Clear funnel filter</button></div>}
    <div className="crm-controls"><div className="crm-segments" aria-label="Lead filters">{[['all','All leads'],['interest','Enquiries & waitlist'],['due','Follow-ups due'],['mine','Assigned to me']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="crm-segments" aria-label="Lead view"><button aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={15}/> List</button><button aria-pressed={view==='board'} onClick={()=>setView('board')}><Columns3 size={15}/> Board</button></div></div>
    <div className="crm-filterbar"><label className="ss-search"><Search size={16}/><input aria-label="Search leads" placeholder="Search name, email or source…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter by stage" value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All stages</option>{Object.entries(leadStages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Filter by source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{[...new Set(data.leads.map(l=>l.source))].sort().map(s=><option key={s}>{s}</option>)}</select><span>{found.length} {found.length===1?'lead':'leads'}</span></div>
    {!data.leads.length?<div className="crm-empty"><span className="crm-empty-icon"><Users size={25}/></span><h2>Add your first lead</h2><p>Keep waitlist replies, applications and offers together. Add a source and next action so you know who to follow up with.</p><button className="ss-button ss-primary" onClick={addLead}><Plus size={16}/> Add lead</button></div>:!found.length?<div className="crm-empty"><h2>No leads match these filters</h2><button className="ss-button" onClick={()=>{setFilter('all');setSearch('');setStage('all');setSource('all');setParams(p=>{p.delete('milestone');p.delete('queue');p.delete('stage');p.delete('source');return p;});}}>Clear filters</button></div>:view==='list'?<div className="crm-table-wrap"><table className="crm-table"><thead><tr><th>Lead</th><th>Stage</th><th>Source</th><th>Next action</th><th>Owner</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{found.map(l=><tr key={l.id}><td><button className="crm-person" onClick={()=>openLead(l.id)}><span className="crm-initials">{l.full_name.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><span><strong>{l.full_name}</strong><small>{l.email}</small></span></button></td><td><StageBadge stage={displayStage(l)}/>{l.payment_status!=='unconfirmed'&&<small className="crm-payment">{l.payment_status==='confirmed'?'Payment recorded':'Refund recorded'}</small>}</td><td>{l.source}<small>{l.source_detail}</small></td><td><span>{l.next_action||'Set next action'}</span><DueLabel due={l.due_on}/></td><td>{data.staff.find(s=>s.user_id===l.owner_id)?.full_name??'Unassigned'}</td><td><button className="crm-icon-button" aria-label={`Open ${l.full_name}`} onClick={()=>openLead(l.id)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>:<div className="crm-board">{Object.entries(leadStages).filter(([key])=>stage==='all'||key===stage).map(([key,label])=>{const leads=found.filter(l=>displayStage(l)===key);return <section key={key} className={`crm-lane ${drop===key?'crm-lane-drop':''}`} onDragOver={e=>{if(!['enrolled','paid'].includes(key)){e.preventDefault();setDrop(key);}}} onDragLeave={()=>setDrop('')} onDrop={e=>{e.preventDefault();void move(e.dataTransfer.getData('text/plain'),key);}}><header><StageBadge stage={key}/><span>{leads.length}</span></header>{leads.map(l=><button key={l.id} className="crm-lead-card" draggable={!['enrolled','paid'].includes(key)&&!moving} onDragStart={e=>e.dataTransfer.setData('text/plain',l.id)} onDragEnd={()=>setDrop('')} onClick={()=>openLead(l.id)} disabled={moving===l.id}><strong>{l.full_name}</strong><small>{l.source}</small><p>{l.next_action||'Set next action'}</p><DueLabel due={l.due_on}/></button>)}{!leads.length&&<p className="crm-lane-empty">{key==='enrolled'?'Linked enrolments appear here':key==='paid'?'Recorded first payments appear here':`No ${label.toLowerCase()} leads`}</p>}</section>;})}</div>}
  </>;
}
function StageBadge({stage}:{stage:string}) {return <Badge tone={stage==='enrolled'||stage==='paid'?'green':stage==='approved'?'blue':stage==='offer_sent'?'purple':stage==='applied'?'blue':'gray'}>{leadStages[stage as keyof typeof leadStages]}</Badge>;}
function DueLabel({due}:{due:string|null}) { if(!due)return null;const state=dueState(due);return <small className={`crm-due ${state==='overdue'||state==='today'?'crm-attention':''}`}><Clock3 size={12}/>{state==='overdue'?'Overdue · ':state==='today'?'Today · ':''}{readableDate(due)}</small>; }

function OnboardingQueue({data,onBooking}:{data:CrmWorkspace;onBooking:(s:CrmStudent)=>void}) {
  const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [tests,setTests]=useState(false);
  const students=data.students.filter(s=>s.status==='active'&&(!s.is_walkthrough||tests));
  const found=students.map(s=>({student:s,state:onboardingState(s.call,s.questionnaire,s.focus)})).filter(({student:s,state})=>[s.name,s.email].join(' ').toLowerCase().includes(search.toLowerCase())&&(filter==='all'||state.key===filter)).sort((a,b)=>(a.state.key==='complete'?1:0)-(b.state.key==='complete'?1:0)||(a.student.call?.booked_at??'9999').localeCompare(b.student.call?.booked_at??'9999'));
  return <><div className="crm-controls"><div className="crm-segments crm-scroll" aria-label="Onboarding status">{[['all','All students'],['not_booked','Awaiting booking'],['booked','Booked'],['notes_due','To complete'],['complete','Complete']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div></div><div className="crm-filterbar"><label className="ss-search"><Search size={16}/><input aria-label="Search onboarding students" placeholder="Search students…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="crm-checkbox"><input type="checkbox" checked={tests} onChange={e=>setTests(e.target.checked)}/> Include my test student</label><span>{found.length} students</span></div>
    {!found.length?<div className="crm-empty"><CalendarDays size={28}/><h2>{students.length?'No students match this view':'Your enrolled students will appear here'}</h2><p>Each student has a questionnaire ready in their record. There is no separate assignment step.</p></div>:<div className="crm-table-wrap"><table className="crm-table crm-onboarding-table"><thead><tr><th>Student</th><th>Status</th><th>Onboarding call</th><th>Ready for coaching</th><th>Next step</th></tr></thead><tbody>{found.map(({student:s,state})=><tr key={s.id}><td><Link className="crm-person" to={studentLink(s)}><StudentAvatar name={s.name} src={s.profile?.photoUrl} size={38}/><span><strong>{s.name}</strong><small>{s.is_walkthrough?'Your test student':s.email}</small></span></Link></td><td><Badge tone={state.tone}>{state.label}</Badge></td><td><button className="crm-date-button" onClick={()=>onBooking(s)}><CalendarDays size={14}/>{s.call?.booked_at?readableDate(s.call.booked_at,true):'Set booking'}</button><small>{data.staff.find(p=>p.user_id===s.call?.owner_id)?.full_name??'Assign coach'}</small></td><td><div className="crm-checkpoints"><Checkpoint done={Boolean(s.profile?.completedAt)} label="Profile"/><Checkpoint done={Boolean(s.call?.completed_at)} label="Call held"/><Checkpoint done={Boolean(s.focus.trim())} label="Coaching focus"/></div></td><td>{state.action==='Confirm call outcome'||state.action==='Check call outcome'||state.key==='not_booked'?<button className="ss-button" onClick={()=>onBooking(s)}>{state.action}<ArrowRight size={14}/></button>:<Link className="ss-button" to={studentLink(s)}>{state.action}<ArrowRight size={14}/></Link>}<Link className="crm-secondary-link" to={studentLink(s)}>Open questionnaire</Link></td></tr>)}</tbody></table></div>}
    <p className="crm-footnote">Booking times are shown in {Intl.DateTimeFormat().resolvedOptions().timeZone.replace(/_/g,' ')}. Onboarding is complete when the call is marked held, the questionnaire is agreed and the coaching focus is saved.</p>
  </>;
}
function Checkpoint({done,label}:{done:boolean;label:string}) {return <span className={done?'crm-check-done':''}><span className="crm-check-dot">{done&&<Check size={10}/>}</span>{label}</span>;}

function LeadPanel({lead,cohortId,staff,activeIds,data,refresh,onClose,onSaved}:{lead?:Lead;cohortId:string;staff:StaffPerson[];activeIds:Set<string>;data:CrmWorkspace;refresh:()=>Promise<void>;onClose:()=>void;onSaved:(lead:Lead)=>Promise<void>}) {
  const [previous,setPrevious]=useState(lead);const [input,setInput]=useState<LeadInput>(lead?leadInput(lead):blankLead(cohortId));const [saved,setSaved]=useState(JSON.stringify(input));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState('details');const [note,setNote]=useState('');const [paymentDirty,setPaymentDirty]=useState(false);const [paymentBusy,setPaymentBusy]=useState(false);
  const dirty=paymentDirty||JSON.stringify(input)!==saved||!!note.trim();useDirtyWarning(dirty);
  const history=useQuery({queryKey:['lead-activity',lead?.id],queryFn:()=>loadLeadActivity(lead!.id),enabled:!!lead});
  const change=<K extends keyof LeadInput>(key:K,value:LeadInput[K])=>setInput(p=>({...p,[key]:value}));
  const close=()=>{if(!busy&&!paymentBusy&&(!dirty||window.confirm('Discard unsaved changes to this lead?')))onClose();};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const record=await saveLead(input,previous);setPrevious(record);setInput(leadInput(record));setSaved(JSON.stringify(leadInput(record)));await onSaved(record);toast.success('Lead saved.');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const addNote=async()=>{setError('');setBusy(true);try{await addLeadNote(lead!.id,note);setNote('');await history.refetch();toast.success('Note added.');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  return <Sheet open onOpenChange={open=>{if(!open)close();}}><SheetContent className="student-success crm-drawer" onEscapeKeyDown={e=>{e.preventDefault();close();}} onInteractOutside={e=>{e.preventDefault();close();}}><div className="crm-drawer-head"><SheetTitle>{lead?lead.full_name:'Add lead'}</SheetTitle><SheetDescription>{lead?lead.email:'Add an enquiry, waitlist reply or application.'}</SheetDescription>{lead&&<div className="crm-inline"><StageBadge stage={leadStage(lead,activeIds)==='enrolled'?'enrolled':lead.stage!=='closed'&&hasPaid(lead,data.payments)?'paid':lead.stage}/>{lead.enrollment_id&&<Link className="ss-link" to={`${successRoot}/${lead.cohort_id}/students/${lead.enrollment_id}?tab=Onboarding`} onClick={e=>{if(dirty&&!window.confirm('Discard unsaved changes and open the student record?'))e.preventDefault();}}>Student record <ArrowRight size={14}/></Link>}</div>}</div>
    {lead&&(lead.email_thread_url||lead.application_url)&&<div className="crm-source-links">{lead.email_thread_url&&<a className="ss-button" href={lead.email_thread_url} target="_blank" rel="noopener noreferrer"><Link2 size={14}/> Open Gmail conversation</a>}{lead.application_url&&<a className="ss-button" href={lead.application_url} target="_blank" rel="noopener noreferrer"><Link2 size={14}/> Open application</a>}</div>}
    {lead&&<div className="crm-tabs"><button type="button" aria-current={tab==='details'?'page':undefined} onClick={()=>setTab('details')}>Details & next action</button><button type="button" aria-current={tab==='activity'?'page':undefined} onClick={()=>setTab('activity')}>Activity</button><button type="button" aria-current={tab==='payments'?'page':undefined} onClick={()=>setTab('payments')}>Payments</button></div>}
    <form onSubmit={submit} className={tab==='details'?'crm-editor':'hidden'}><fieldset disabled={busy}>
      <div className="crm-form-section"><h3>Contact</h3><div className="crm-form-grid"><label className="ss-field">Full name<input required maxLength={160} value={input.full_name} onChange={e=>change('full_name',e.target.value)}/></label><label className="ss-field">Email<input type="email" required maxLength={254} value={input.email} onChange={e=>change('email',e.target.value)} readOnly={Boolean(lead?.enrollment_id)}/></label></div></div>
      <div className="crm-form-section"><h3>Pipeline & follow-up</h3><div className="crm-form-grid"><label className="ss-field">Sales stage<select value={input.stage} disabled={Boolean(lead?.enrollment_id&&activeIds.has(lead.enrollment_id))} onChange={e=>change('stage',e.target.value as LeadStage)}>{Object.entries(leadStages).filter(([k])=>!['enrolled','paid'].includes(k)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><OwnerField staff={staff} value={input.owner_id} change={v=>change('owner_id',v)}/></div><label className="ss-field">Next action<input placeholder="e.g. Reply with the offer and answer their question" maxLength={1000} value={input.next_action} onChange={e=>change('next_action',e.target.value)}/></label><DateField label="Follow-up date" value={input.due_on} change={v=>change('due_on',v)}/>{lead?.next_action&&<button className="crm-text-button" type="button" onClick={()=>{change('next_action','');change('due_on',null);}}>Clear completed follow-up</button>}</div>
      <div className="crm-form-section"><h3>Where they came from</h3><label className="ss-field">First contact<select value={input.first_contact_channel} onChange={e=>change('first_contact_channel',e.target.value)}>{leadChannels.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label className="ss-field">Original source<input list="crm-sources" required maxLength={100} value={input.source} onChange={e=>change('source',e.target.value)}/><datalist id="crm-sources">{leadSources.map(s=><option key={s} value={s}/>)}</datalist></label><p className="crm-footnote">Keep the original source when they later apply. Use Not recorded when it is unknown.</p><label className="ss-field">Source detail<input placeholder="Campaign, referral name or original conversation" maxLength={1000} value={input.source_detail} onChange={e=>change('source_detail',e.target.value)}/></label></div>
      <div className="crm-form-section"><h3>Context for the onboarding call</h3><label className="ss-field">Goals and application notes<textarea rows={4} maxLength={4000} value={input.goals} onChange={e=>change('goals',e.target.value)} placeholder="What they want help with, in their own words"/></label><label className="ss-field">Music link<input type="url" placeholder="https://" maxLength={2048} value={input.music_url??''} onChange={e=>change('music_url',e.target.value||null)}/></label><label className="ss-field">Gmail conversation<input type="url" placeholder="https://mail.google.com/…" maxLength={2048} value={input.email_thread_url??''} onChange={e=>change('email_thread_url',e.target.value||null)}/></label><label className="ss-field">Application link<input type="url" placeholder="https://" maxLength={2048} value={input.application_url??''} onChange={e=>change('application_url',e.target.value||null)}/></label></div>

    </fieldset><div className="crm-drawer-footer">{error&&<p role="alert" className="ss-error">{error}</p>}<span>{JSON.stringify(input)!==saved?'Unsaved changes':lead?'Saved':'New lead'}</span><button type="submit" disabled={busy} className="ss-button ss-primary">{busy?'Saving…':'Save lead'}</button></div></form>
    {lead&&<div hidden={tab!=='payments'}><LeadPayments onDirty={setPaymentDirty} onBusy={setPaymentBusy} lead={lead} payments={data.payments} currency={data.settings.currency} refresh={async()=>{await refresh();await history.refetch();}}/></div>}
    {tab==='activity'&&lead&&<div className="crm-activity"><label className="ss-field">Add a note<textarea value={note} maxLength={6000} onChange={e=>setNote(e.target.value)} placeholder="What was discussed? What needs to happen next?"/></label><button className="ss-button ss-primary" disabled={busy||!note.trim()} onClick={()=>void addNote()}><Plus size={15}/> Add note</button>{error&&<p className="ss-error" role="alert">{error}</p>}{history.isPending?<SuccessLoading/>:history.isError?<SuccessError error={history.error} retry={()=>void history.refetch()}/>:<ol className="crm-timeline">{[...(history.data??[])].reverse().map(a=><li key={a.id}><span className="crm-timeline-dot"/><div><strong>{a.kind==='note'?'Note':a.kind==='created'?'Lead added':'Record updated'}</strong><p>{a.body}</p><small>{readableDate(a.created_at,true)} · {staff.find(s=>s.user_id===a.actor_id)?.full_name??'System'}</small></div></li>)}</ol>}</div>}
  </SheetContent></Sheet>;
}
function OwnerField({staff,value,change}:{staff:StaffPerson[];value:string|null;change:(v:string|null)=>void}) {return <label className="ss-field">Owner<select value={value??''} onChange={e=>change(e.target.value||null)}><option value="">Unassigned</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.full_name}</option>)}</select></label>;}
function BookingPanel({student:s,staff,close,saved}:{student:CrmStudent;staff:StaffPerson[];close:()=>void;saved:()=>Promise<void>}) {
  const [date,setDate]=useState(localDateTime(s.call?.booked_at??null).slice(0,10));const [time,setTime]=useState(localDateTime(s.call?.booked_at??null).slice(11));const [held,setHeld]=useState(Boolean(s.call?.completed_at));const [owner,setOwner]=useState(s.call?.owner_id??null);const [notes,setNotes]=useState(s.call?.notes??'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const dirty=date!==localDateTime(s.call?.booked_at??null).slice(0,10)||time!==localDateTime(s.call?.booked_at??null).slice(11)||held!==Boolean(s.call?.completed_at)||owner!==(s.call?.owner_id??null)||notes!==(s.call?.notes??'');useDirtyWarning(dirty);
  const dismiss=()=>{if(!busy&&(!dirty||window.confirm('Discard unsaved booking changes?')))close();};
  return <Sheet open onOpenChange={open=>{if(!open)dismiss();}}><SheetContent className="student-success crm-drawer" onEscapeKeyDown={e=>{e.preventDefault();dismiss();}} onInteractOutside={e=>{e.preventDefault();dismiss();}}><SheetTitle>Onboarding call</SheetTitle><SheetDescription>{s.name} · {s.email}</SheetDescription><form className="crm-editor" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{if(time&&!date)throw new Error('Choose a call date as well as a time.');await saveOnboardingCall(s.id,{booked_at:date?new Date(`${date}T${time}`).toISOString():null,completed_at:held?(s.call?.completed_at??new Date().toISOString()):null,owner_id:owner,notes},s.call);await saved();toast.success('Onboarding booking saved.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><fieldset disabled={busy}><div className="crm-form-section"><OwnerField staff={staff} value={owner} change={setOwner}/><DateField label="Call date" value={date||null} change={v=>{setDate(v??'');if(!v)setTime('');}}/><label className="ss-field">Call time<input type="text" placeholder="19:00" pattern="([01][0-9]|2[0-3]):[0-5][0-9]" required={Boolean(date)} value={time} onChange={e=>setTime(e.target.value)}/><span className="ss-muted">24-hour time, shown in {Intl.DateTimeFormat().resolvedOptions().timeZone.replace(/_/g,' ')}</span></label><label className="crm-checkbox"><input type="checkbox" checked={held} onChange={e=>setHeld(e.target.checked)}/> The onboarding call has taken place</label><label className="ss-field">Booking notes<textarea maxLength={4000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Rescheduling details or anything Rob needs before the call"/></label></div><p className="crm-footnote">This records the booking for staff. It does not send a calendar invitation.</p></fieldset><div className="crm-drawer-footer">{error&&<p role="alert" className="ss-error">{error}</p>}<span>{dirty?'Unsaved changes':'Booking details'}</span><button className="ss-button ss-primary" disabled={busy} type="submit">{busy?'Saving…':'Save booking'}</button></div></form></SheetContent></Sheet>;
}

function DateField({label,value,change}:{label:string;value:string|null;change:(v:string|null)=>void}) {
  const [open,setOpen]=useState(false);
  const choose=(date:Date|undefined)=>{change(date?localDay(date):null);setOpen(false);};
  const selected=value?new Date(`${value}T12:00:00`):undefined;
  return <div className="ss-field crm-date-field"><span>{label}</span><button type="button" className="crm-date-input" aria-label={`${label}: ${value?readableDate(value):'Choose date'}`} aria-expanded={open} onClick={()=>setOpen(!open)}><CalendarDays size={14}/>{value?readableDate(value):'Choose date'}</button>{open&&<div className="crm-calendar"><Calendar mode="single" selected={selected} defaultMonth={selected} onSelect={choose} weekStartsOn={1} classNames={{day_selected:'crm-calendar-selected',day_today:'crm-calendar-today',head_cell:'crm-calendar-weekday',day_outside:'crm-calendar-outside'}}/><div className="crm-date-shortcuts"><button type="button" onClick={()=>choose(new Date())}>Today</button><button type="button" onClick={()=>{const d=new Date();d.setDate(d.getDate()+1);choose(d);}}>Tomorrow</button><button type="button" onClick={()=>choose(undefined)}>Clear</button></div></div>}</div>;
}
