import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck, Mail, Target, Users, Wallet, Info } from 'lucide-react';
import { Sheet, SheetContent, SheetDescription, SheetTitle } from '@/components/ui/sheet';
import { crmRoot, dueState, localDay, readableDate, type Lead } from '../crm';
import { currencies, launchAnalytics, money, parseMoney, hasPaid, type LaunchSettings, type RecordedPayment, type FunnelStep } from '../crmAnalytics';
import { recordPayment, saveLaunchSettings, voidPayment, type CrmWorkspace } from '../crmApi';
import { toast } from 'sonner';

const errorText=(e:unknown)=>e instanceof Error?e.message:'Unable to save. Please try again.';
const rate=(n:number|null)=>n===null?'—':`${Math.round(n*1000)/10}%`;
export function LaunchOverview({data,cohortId,editTargets,openLead}:{data:CrmWorkspace;cohortId:string;editTargets:()=>void;openLead:(id:string)=>void}) {
  const report=launchAnalytics(data.leads,data.milestones,data.payments,data.students);
  const {settings}=data;const currency=settings.currency;const cash=currency?report.totals[currency]??{gross:0,refunds:0,net:0}:null;
  const totalValue=settings.seat_price_minor?settings.seat_price_minor*settings.capacity:null;
  const queueLink=(query:string)=>`${crmRoot}/leads?cohort=${cohortId}&${query}`;
  const waiting=data.leads.filter(l=>l.stage!=='closed'&&!l.enrollment_id&&!hasPaid(l,data.payments));
  const due=waiting.filter(l=>['today','overdue'].includes(dueState(l.due_on)));
  const tasks=[
    {title:'Reply to enquiries & handraisers',count:waiting.filter(l=>['new','waitlist'].includes(l.stage)).length,copy:'Open their conversation, answer questions and record the next follow-up.',query:'queue=interest',icon:Mail},
    {title:'Review applications',count:waiting.filter(l=>l.stage==='applied').length,copy:'Read the Typeform answers, listen to their music and record your decision.',query:'stage=applied',icon:ClipboardCheck},
    {title:'Send approved applicants the offer',count:waiting.filter(l=>l.stage==='approved').length,copy:'Send the offer and payment link, then mark the offer as sent.',query:'stage=approved',icon:CheckCircle2},
    {title:'Follow up on payment',count:waiting.filter(l=>l.stage==='offer_sent').length,copy:'Check who has paid and follow up with anyone still deciding.',query:'stage=offer_sent',icon:Wallet},
  ];
  return <div className="crm-launch">
    <div className="crm-launch-metrics">
      <section className="crm-seat-target"><div className="crm-metric-label"><Users size={17}/> Confirmed places <button onClick={editTargets}>Edit targets</button></div><strong>{report.confirmed.length}<span> / {settings.capacity}</span></strong><div className="crm-meter" role="progressbar" aria-label="Seats filled" aria-valuemin={0} aria-valuemax={Math.max(settings.capacity,report.confirmed.length)} aria-valuenow={report.confirmed.length}><i style={{width:`${Math.min(100,report.confirmed.length/settings.capacity*100)}%`}}/></div><p>{report.confirmed.length>settings.capacity?`${report.confirmed.length-settings.capacity} above target`:`${settings.capacity-report.confirmed.length} seats to fill`} · first payment recorded</p></section>
      <section><div className="crm-metric-label"><Target size={17}/> Full cohort value</div><strong>{currency&&totalValue?money(totalValue,currency):'Not set'}</strong><p>{currency&&settings.seat_price_minor?`${settings.capacity} seats × ${money(settings.seat_price_minor,currency)} ${currency}`:'Set your price and currency'}<br/>Value at capacity, before refunds or discounts</p></section>
      <section><div className="crm-metric-label"><CircleDollarSign size={17}/> Cash collected {currency&&<span>{currency}</span>}</div><strong>{cash&&currency?money(cash.net,currency):'Not set'}</strong><p>{cash&&currency?`${money(cash.gross,currency)} received · ${money(cash.refunds,currency)} refunded`:'Choose a reporting currency'}<br/>Recorded receipts after refunds, before fees</p>{settings.cash_target_minor&&cash&&currency?<small>{rate(cash.net/settings.cash_target_minor)} of {money(settings.cash_target_minor,currency)} cash target</small>:<button className="crm-text-button" onClick={editTargets}>Set a cash collection target</button>}</section>
      <section><div className="crm-metric-label"><ClipboardCheck size={17}/> Contact → first payment</div><strong>{rate(report.leadToPaid)}</strong><p>{report.ids.paid.size} of {data.leads.length} known contacts<br/>All recorded activity for this cohort</p></section>
    </div>
    <div className="crm-data-note"><Info size={16}/><div><strong>Recorded data only</strong><span> Gmail replies are imported. {data.intake.find(c=>c.provider==='typeform')?.status==='connected'?'Typeform intake is connected.':'Typeform is not connected yet, so application totals and conversion rates are incomplete.'} Payments are recorded by staff until checkout is connected.{report.unknownAmounts>0?` ${report.unknownAmounts} payment record(s) still need amounts.`:''}</span></div></div>
    <section className="crm-report-card"><header><div><h2>Launch funnel</h2><p>From first contact to the start of coaching. Click a stage to see the people behind it.</p></div><span className="crm-report-scope">This cohort · all time</span></header>
      <div className="crm-funnel">{report.steps.map((step,i)=><Link key={step.key} to={queueLink(`milestone=${step.key}`)} className={`crm-funnel-step crm-step-${i}`}><span className="crm-step-number">0{i+1}<ChevronRight size={14}/></span><h3>{step.label}</h3><strong>{step.count}</strong><div className="crm-funnel-track"><i style={{width:`${data.leads.length?step.count/data.leads.length*100:0}%`}}/></div><span className="crm-funnel-rate">{i===0?`${report.waitlist} currently on the waitlist`:step.base?`${rate(step.rate)} · ${step.converted} of ${step.base} from prior step`:'No previous-stage contacts yet'}</span>{step.skipped>0&&<small>{step.skipped} without a recorded prior step</small>}</Link>)}</div>
      <details className="crm-report-definitions"><summary>How these numbers work</summary><p>Each person counts once at each stage they have reached. Moving them forward or closing their enquiry keeps that history. Direct applicants can enter without being waitlisted. A conversion rate counts people with both stages recorded, divided by everyone in the previous stage. Missing stages are not assumed. First payment counts anyone who has paid, including later refunds; confirmed places excludes fully refunded and closed contacts. Onboarding here includes people linked to a lead whose call, agreed questionnaire and coaching focus are complete. Offer-doc views are not tracked or included as identifiable contacts.</p></details>
    </section>
    <section className="crm-report-card"><header><div><h2>What needs doing</h2><p>These are working queues. You decide who to accept and when to follow up.</p></div><Link className="crm-queue-link" to={queueLink('queue=due')}>{due.length} follow-ups due <ArrowRight size={15}/></Link></header><div className="crm-action-grid">{tasks.map(({title,count,copy,query,icon:Icon})=><Link key={title} to={queueLink(query)}><div className="crm-action-heading"><Icon size={18}/><strong>{count}</strong></div><h3>{title}</h3><p>{copy}</p><span>Open queue <ArrowRight size={14}/></span></Link>)}</div>
      <details className="crm-howto"><summary>How to use the CRM day to day</summary><ol><li><strong>Work the follow-ups.</strong> Open a contact, click their Gmail conversation, reply there, then set an owner, next action and date here. Changing a stage does not send an email.</li><li><strong>Review the application.</strong> Their Typeform answers belong on the same contact. Mark suitable applicants Approved. Mark declined or withdrawn enquiries Closed and leave a note.</li><li><strong>Send the offer, then record actual payments.</strong> Mark Offer sent after you send it. In Payments, add each completed instalment and any refund using its transaction reference. A payment entry does not charge anyone or grant portal access.</li><li><strong>Complete onboarding.</strong> Once enrolled, their student record appears in Onboarding. Arrange the call and complete their questionnaire and first coaching focus.</li></ol></details>
    </section>
    <div className="crm-report-columns"><section className="crm-report-card"><header><div><h2>Where leads come from</h2><p>Original source is retained when someone later applies.</p></div></header><div className="crm-table-scroll"><table className="crm-source-table"><thead><tr><th>Source</th><th>Contacts</th><th>Applied</th><th>Paid</th><th>Contact → paid</th><th>Cash{currency?` (${currency})`:''}</th></tr></thead><tbody>{report.sources.map(row=><tr key={row.source}><td><Link to={queueLink(`source=${encodeURIComponent(row.source)}`)}>{row.source}<ArrowRight size={12}/></Link></td><td>{row.leads}</td><td>{row.applied}</td><td>{row.paid}</td><td>{rate(row.paid/row.leads)}</td><td>{currency?money(row.totals[currency]?.net??0,currency):'—'}</td></tr>)}</tbody></table></div></section>
    <section className="crm-report-card crm-next-contact"><header><div><h2>Next follow-ups</h2><p>Due today or overdue.</p></div></header>{due.length?due.sort((a,b)=>(a.due_on??'').localeCompare(b.due_on??'')).slice(0,4).map(l=><button key={l.id} onClick={()=>openLead(l.id)}><div><strong>{l.full_name}</strong><p>{l.next_action}</p><small>{readableDate(l.due_on)} · {data.staff.find(s=>s.user_id===l.owner_id)?.full_name??'Unassigned'}</small></div><ChevronRight size={17}/></button>):<p className="crm-report-empty">No follow-ups due.</p>}</section></div>
    {Object.keys(report.totals).some(c=>c!==currency)&&<section className="crm-report-card"><header><div><h2>Other currencies received</h2><p>Kept separate. No exchange-rate conversions are assumed.</p></div></header><div className="crm-other-cash">{Object.entries(report.totals).filter(([c])=>c!==currency).map(([c,t])=><span key={c}>{c} <strong>{money(t.net,c)}</strong></span>)}</div></section>}
  </div>;
}

export function LaunchTargetsPanel({cohortId,settings,close,saved}:{cohortId:string;settings:LaunchSettings;close:()=>void;saved:()=>Promise<void>}) {
  const [capacity,setCapacity]=useState(settings.capacity);const [currency,setCurrency]=useState(settings.currency??'');const [price,setPrice]=useState(settings.seat_price_minor?String(settings.seat_price_minor/100):'');const [cash,setCash]=useState(settings.cash_target_minor?String(settings.cash_target_minor/100):'');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <Sheet open onOpenChange={open=>{if(!open&&!busy)close();}}><SheetContent className="student-success crm-drawer"><SheetTitle>Launch targets</SheetTitle><SheetDescription>Set the seats and price for this cohort. The cash target is optional.</SheetDescription><form className="ss-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await saveLaunchSettings(cohortId,{capacity,currency:currency||null,seat_price_minor:price?parseMoney(price):null,cash_target_minor:cash?parseMoney(cash):null});await saved();toast.success('Launch targets saved.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><fieldset disabled={busy} className="ss-form"><label className="ss-field">Seat target<input type="number" min={1} max={1000} required value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label className="ss-field">Currency<select value={currency} required={Boolean(price||cash)} onChange={e=>setCurrency(e.target.value)}><option value="">Choose currency</option>{currencies.map(c=><option key={c}>{c}</option>)}</select></label><label className="ss-field">Price per seat<input inputMode="decimal" placeholder="2,497" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="ss-field">Cash collection target (optional)<input inputMode="decimal" value={cash} onChange={e=>setCash(e.target.value)} placeholder="Amount you want collected during launch"/></label><p className="crm-footnote">Full cohort value is seats × price. With instalments, your launch cash target may be lower. Targets never create payment records.</p></fieldset>{error&&<p className="ss-error" role="alert">{error}</p>}<button className="ss-button ss-primary" disabled={busy}>Save targets</button></form></SheetContent></Sheet>;
}

export function LeadPayments({lead,payments,currency,refresh,onDirty,onBusy}:{lead:Lead;payments:RecordedPayment[];currency:string|null;refresh:()=>Promise<void>;onDirty:(v:boolean)=>void;onBusy:(v:boolean)=>void}) {
  const records=payments.filter(p=>p.lead_id===lead.id).sort((a,b)=>b.paid_on.localeCompare(a.paid_on)||b.created_at.localeCompare(a.created_at));
  const [adding,setAdding]=useState(false);const [kind,setKind]=useState<'payment'|'refund'>('payment');const [amount,setAmount]=useState('');const [unit,setUnit]=useState(currency??'USD');const [date,setDate]=useState(localDay());const [provider,setProvider]=useState('stripe');const [reference,setReference]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [voidId,setVoidId]=useState('');const [reason,setReason]=useState('');
  useEffect(()=>{onDirty((adding&&Boolean(amount||reference||note))||Boolean(voidId&&reason));},[adding,amount,reference,note,voidId,reason,onDirty]);
  useEffect(()=>{onBusy(busy);},[busy,onBusy]);
  return <div className="crm-payment-ledger"><div className="crm-ledger-intro"><Wallet size={20}/><div><h3>Payments & refunds</h3><p>Record completed transactions, one entry per instalment. Amounts update the launch dashboard.</p></div></div>
    {lead.payment_status!=='unconfirmed'&&!records.some(p=>!p.voided_at)&&<p className="ss-notice">Earlier status: {lead.payment_status}. No amount recorded. Add the actual transactions below to include them in cash totals.</p>}
    {!adding?<button className="ss-button ss-primary" onClick={()=>setAdding(true)}>Record payment or refund</button>:<form className="ss-form crm-payment-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await recordPayment({lead_id:lead.id,kind,amount_minor:parseMoney(amount),currency:unit,paid_on:date,provider,reference,note});setAdding(false);setAmount('');setReference('');setNote('');await refresh();toast.success('Transaction recorded.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><fieldset disabled={busy} className="ss-form"><div className="crm-form-grid"><label className="ss-field">Transaction type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="payment">Payment received</option><option value="refund">Refund issued</option></select></label><label className="ss-field">Payment provider<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="stripe">Stripe</option><option value="paypal">PayPal</option><option value="whop">Whop</option><option value="bank">Bank transfer</option><option value="other">Other</option></select></label><label className="ss-field">Amount received or refunded<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label className="ss-field">Currency<select value={unit} onChange={e=>setUnit(e.target.value)}>{currencies.map(c=><option key={c}>{c}</option>)}</select></label></div><label className="ss-field">Transaction date<input type="date" required max={localDay()} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="ss-field">Transaction reference<input required maxLength={300} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Payment or refund ID from the provider"/></label><label className="ss-field">Notes (optional)<textarea maxLength={2000} rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. Instalment 1 of 3"/></label><p className="crm-footnote">Use the actual amount received, before processor fees. This records an existing transaction; it does not charge, refund, email or grant access.</p></fieldset>{error&&<p className="ss-error" role="alert">{error}</p>}<div className="crm-inline"><button type="submit" className="ss-button ss-primary" disabled={busy}>Save transaction</button><button type="button" className="ss-button" disabled={busy} onClick={()=>{setAdding(false);setAmount('');setReference('');setNote('');setError('');}}>Cancel</button></div></form>}
    <div className="crm-ledger-list">{records.length?records.map(p=><article key={p.id} className={p.voided_at?'crm-voided':''}><div className="ss-row"><strong>{p.kind==='refund'?'−':''}{money(p.amount_minor,p.currency)} <small>{p.currency}</small></strong><span className={`crm-badge ${p.voided_at?'crm-gray':p.kind==='refund'?'crm-amber':'crm-green'}`}>{p.voided_at?'Voided':p.kind==='refund'?'Refund':'Payment'}</span></div><p>{readableDate(p.paid_on)} · {p.provider} · {p.reference}</p>{p.note&&<p>{p.note}</p>}{p.voided_at?<p>Correction: {p.void_reason}</p>:voidId===p.id?<form className="ss-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await voidPayment(p.id,reason);setVoidId('');setReason('');await refresh();toast.success('Incorrect record voided.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><label className="ss-field">Reason for correction<input required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why was this entry incorrect?"/></label><p className="crm-footnote">Voiding corrects an entry. For money actually returned to a student, record a refund instead.</p>{error&&<p className="ss-error" role="alert">{error}</p>}<div className="crm-inline"><button disabled={busy} className="ss-button">Void incorrect entry</button><button disabled={busy} type="button" className="crm-text-button" onClick={()=>setVoidId('')}>Cancel</button></div></form>:<button className="crm-text-button" onClick={()=>{setVoidId(p.id);setError('');}}>Correct this record</button>}</article>):<p className="crm-report-empty">No transaction amounts recorded yet.</p>}</div>
  </div>;
}
export type { FunnelStep };
