import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const compile=(path)=>ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText;
const url=js=>`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`;
const planUrl=url(compile('src/mentorship/onboardingPlan.ts'));
const {emptyOnboardingPlan}=await import(planUrl);
const {normaliseLead,blankLead,onboardingState,leadStage,dueState}=await import(url(compile('src/mentorship/crm.ts').replace("'./onboardingPlan'",JSON.stringify(planUrl))));
const input={...blankLead('cohort'),full_name:' Name ',email:' NAME@EXAMPLE.COM '};
assert.equal(normaliseLead(input).email,'name@example.com');
assert.throws(()=>normaliseLead({...input,due_on:'2026-10-12'}),/next action/);
assert.throws(()=>normaliseLead({...input,payment_status:'confirmed'}),/payment reference/);
assert.throws(()=>normaliseLead({...input,music_url:'javascript:alert(1)'}),/HTTPS/);
assert.throws(()=>normaliseLead({...input,music_url:'https://user:pass@example.com'}),/login details/);
assert.equal(leadStage({...input,stage:'waitlist',enrollment_id:'enrolled'},new Set()),'waitlist');
assert.equal(leadStage({...input,stage:'waitlist',enrollment_id:'enrolled'},new Set(['enrolled'])),'enrolled');
assert.equal(dueState('2026-10-05','2026-10-07'),'overdue');
assert.equal(dueState('2026-10-07','2026-10-07'),'today');
const call={completed_at:null,booked_at:'2026-10-12T18:00:00Z'};
assert.equal(onboardingState(undefined,null,'').key,'not_booked');
assert.equal(onboardingState(call,null,'',Date.parse('2026-10-07')).key,'booked');
assert.equal(onboardingState(call,null,'',Date.parse('2026-10-13')).action,'Check call outcome');
const plan=emptyOnboardingPlan();
plan.status='agreed';
assert.notEqual(onboardingState({...call,completed_at:'2026-10-12'},plan,'Focus').key,'complete');
plan.musicReviewed=true;
Object.assign(plan.answers,{goal:'Finish a song',music:'Track v2',focus:'Hook',practice:'Shorter intro',listenFor:'Hook arrives sooner'});
assert.equal(onboardingState(call,plan,'Focus').action,'Confirm call outcome');
assert.equal(onboardingState({...call,completed_at:'2026-10-12'},plan,'').action,'Set coaching focus');
assert.equal(onboardingState({...call,completed_at:'2026-10-12'},plan,'Focus').key,'complete');
console.log('CRM: normalized identity, payment evidence, safe links, enrollment stage, due dates, and onboarding completeness passed.');
